### ISSUE TITLE
Generator throws exception

### ISSUE THREAD

**Issue by ekortright** [tinfoil/devise-two-factor#236]
Brand new Rails 7.0.4.3 app with Ruby 3.2.1 running on Rocky Linux 9 in a Docker container.  Gems: Devise 4.9.0, Devise-Two-Factor 5.0.0, openssl 3.1.0.

After running the migration to create the users table from the initial Devise installation, running `bin/rails generate devise_two_factor User` results in an exception (see below).

Question 1: is there anything I can do to figure out if the problem has something to do with my setup?

Question 2: in the meantime can I skip the generator and just perform the configuration manually based on the README?

Thanks.

<pre>$ bin/rails g devise_two_factor User
/home/rocky/ruby-3.2.1/lib/ruby/3.2.0/openssl/pkcs5.rb:14:in `pbkdf2_hmac': no implicit conversion of nil into String (TypeError)
	from /home/rocky/ruby-3.2.1/lib/ruby/3.2.0/openssl/pkcs5.rb:14:in `pbkdf2_hmac'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/activesupport-7.0.4.3/lib/active_support/key_generator.rb:40:in `generate_key'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/encryption/key_generator.rb:33:in `derive_key_from'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/encryption/key.rb:19:in `derive_from'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/encryption/derived_secret_key_provider.rb:8:in `block in initialize'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/encryption/derived_secret_key_provider.rb:8:in `collect'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/encryption/derived_secret_key_provider.rb:8:in `initialize'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/encryption/configurable.rb:25:in `new'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/encryption/configurable.rb:25:in `configure'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/activerecord-7.0.4.3/lib/active_record/railtie.rb:331:in `block in &lt;class:Railtie&gt;'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:32:in `run'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/rocky/ruby-3.2.1/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /home/rocky/ruby-3.2.1/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/rocky/ruby-3.2.1/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/rocky/ruby-3.2.1/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/rocky/ruby-3.2.1/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /home/rocky/ruby-3.2.1/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /home/rocky/ruby-3.2.1/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/rocky/ruby-3.2.1/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /home/rocky/ruby-3.2.1/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:372:in `initialize!'
	from /home/rocky/rails/config/environment.rb:5:in `&lt;main&gt;'
	from &lt;internal:/home/rocky/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb&gt;:37:in `require'
	from &lt;internal:/home/rocky/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb&gt;:37:in `require'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/application.rb:348:in `require_environment!'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/actions.rb:28:in `require_environment!'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/commands/generate/generate_command.rb:21:in `perform'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command/base.rb:87:in `perform'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/command.rb:48:in `invoke'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/railties-7.0.4.3/lib/rails/commands.rb:18:in `&lt;main&gt;'
	from &lt;internal:/home/rocky/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb&gt;:37:in `require'
	from &lt;internal:/home/rocky/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb&gt;:37:in `require'
	from /home/rocky/ruby-3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:4:in `&lt;main&gt;'
</pre>

**Comment by ekortright** [comment]
This seems to be a problem with my installation, not related to Devise-Two-Factor.  Closing.
